Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -616,7 +616,7 @@ jobs:
     strategy:
       fail-fast: false
     runs-on: ubuntu-24.04
-    name: test default FreeBSD
+    name: test default error FreeBSD
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
@@ -642,6 +642,38 @@ jobs:
       if: steps.testerr.outcome != 'failure'
       run: |
         echo "The step was expected to fail, but it succeeded!"
+        exit 1
+
+  testpass:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default success FreeBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ vars.SEC_VBOX }}
+      GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in FreeBSD
+      id: testpass
+      continue-on-error: true 
+      uses: vmactions/freebsd-vm@54cb9ae69f9cee1ce8ac4340293c852585dd5bf2
+      with:
+        envs: 'MYTOKEN MYTOKEN2'
+        prepare: |
+          
+        mem: 4096
+        usesh: true
+        debug: true
+        run: |
+          echo "this is a normal command"
+          exit 0
+    - name: Verify that the previous step succeeded
+      if: steps.testpass.outcome != 'success'
+      run: |
+        echo "The step was expected to succeed, but it failed!"
         exit 1
 
 
