Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -99,6 +99,80 @@ jobs:
           sysctl hw.physmem
           sysctl hw.usermem
 
+  testnfs:
+    strategy:
+      matrix:
+        release: [ "13.2", "13.3", "13.4", "14.0", "14.1", "14.2", "15.0", ""]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest"]
+    runs-on: ${{ matrix.runs }}
+    name: nfs FreeBSD
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      DEBUG: 1
+    steps:
+    - uses: actions/checkout@v4
+    - name: Creating Web console
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
+    - name: Test in FreeBSD
+      id: test
+      uses: vmactions/freebsd-vm@78151834d60f3d818d2a7aabbf095c520a03882c
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          pkg install -y curl
+        release: ${{ matrix.release }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: nfs
+        run: |
+          ls -lah /root/work
+          tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+          pwd
+          ls -lah
+          whoami
+          env
+          freebsd-version
+          sysctl hw.model
+          sysctl hw.ncpu
+          sysctl hw.physmem
+          sysctl hw.usermem
+
+    - name: Test NAT
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      shell: freebsd {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+          pwd
+          ls -lah
+          whoami
+          env
+          freebsd-version
+          sysctl hw.model
+          sysctl hw.ncpu
+          sysctl hw.physmem
+          sysctl hw.usermem
+
 
   test:
     strategy:
